# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2b09ebeeb6fe752b42472b020c5822a8407437716cc2bef9cfd27cecbf09ad54735c0eff0887aec141bfbdde45fa6f46ca720651243f5091319f68e71d53b1

test:
  secret_key_base: c2a8efb45d8be49ea5b050300155a0d03fc6f8d280e242409c4e0a30dce976e3261b6dcd25db65aa69bf7b03d928a2693347bec7af33900bd6c4a3096b4adf52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
